### PR TITLE
Add message class

### PR DESCRIPTION
**Pull request by drewwwwwww**

### CODE REVIEW

**Comment by drewwwwwww** [comment]
Looks fantastic; amazing; well done!

**Comment by eyong0** [comment]
where is ur documentation

**Comment by drewwwwwww** [comment]
> where is ur documentation

https://www.youtube.com/watch?v=YbgT-H39cnQ

**Comment by eyong0** [comment]
> 
> 
> > where is ur documentation
> 
> https://www.youtube.com/watch?v=YbgT-H39cnQ

this isnt documentation

- [x] documentation

**Pull request merged**
